# Site settings
title: Judiskt liv
subtitle: Upptäck det judiska
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by HTML5 Up<br>
  ported to Jekyll by APEHEX<br>
  and released under the Creative Commons.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px_url:
facebook_url: https://github.com/apehex
github_url:
gitlab_url:
instagram_url: https://github.com/apehex
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://github.com/apehex

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Recaptcha in forms
recaptcha:
  sitekey: 6Lc1dcgUAAAAADahcuY9cIFM4iKqezKYOgfO_-Cw
  secretkey:

# Collections
collections:
  pages:
    output: true # Ensures the collection is rendered as pages
    permalink: /:name/ # Customize the URL structure
  artiklar:
    output: true
    permalink: /artiklar/:name/
  judiska-folket:
    output: true
    permalink: /judiska-folket/:name/
  tro:
    output: true
    permalink: /tro/:name/
  historia:
    output: true
    permalink: /historia/:name/
  kultur:
    output: true
    permalink: /kultur/:name/
  judiskt-liv-i-sverige:
    output: true
    permalink: /judiskt-liv-i-sverige/:name/
  authors:
    output: true
    permalink: /forfattare/:name/
  categories:
    output: true
    permalink: /kategorier/:name/
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  - scope:
      path: ""
    values:
      menu: default
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "fr"
    values:
      lang: "fr"

google:
  analytics:
    gtag: ""

# Build settings
permalink: pretty
markdown: kramdown
sass:
  sourcemap: never
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Publication settings
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
#author: apehex
# Exclude from processing

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://judisktliv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: judisktliv
# Exclude from processing
